export const TRACKS_TYPE = {
    SET_TRACKSLIST: "SET_TRACKSLIST",
    SET_TRACK: "SET_TRACK",
    IS_PLAYING: "IS_PLAYING",
    SET_LOADING: "SET_LOADING",
    SET_ERROR: "SET_ERROR",
    SET_LIKE: "SET_LIKE",
    SET_DISLIKE: "SET_DISLIKE"
}

